name: End-to-end tests
on: push
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: read
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1,2]
    permissions:
      contents: write
        
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: |
            cypress/e2e/spec.cy.js
            cypress/e2e/testes-api.cy.js
          parallel: true
          record: true
          group: 'Cypres Tests'

      - name: Commit performance metrics to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # O arquivo a ser commitado no repositório.
          # Certifique-se de que o arquivo está no local correto no runner (ex: metrics/performance-metrics.json)
          file_pattern: metrics/performance-metrics.json 
          
          # Define a mensagem de commit
          commit_message: "feat: Atualiza metrics de performance [Automated Commit]"
          
          # Define o autor do commit (substitua com seus dados)
          commit_user_name: "Adenilson Silva (Automated)"
          commit_user_email: "adenilson.silva@examplo.com"
    
      #- name: Upload Cypress videos
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: cypress-videos
      #    path: cypress/videos/**/*.mp4